openapi: 3.0.0
info:
  version: '0.1'
  title: Allowlist Access API
  description: Access points to allowlist dynamodb

paths: 
  /allowlist/get_list/{org_id}/{repo_id}:
    get:
      summary: Returns a json list of all allowlist terms. 
        If with_info is set to true it will return a list of objects with associated information, else it will just return a list of strings.
      parameters:
        - name: org_id
          in: path
          required: true
          description: The ID of the organization to access
          schema:
            type: integer
        - name: repo_id
          in: path
          required: true
          description: The ID of the repository you are trying to access the whitelist for
          schema:
            type: integer
        - name: with_info
          in: query
          required: false
          description: Should the response also contain extra information related to whitelist terms
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  repo_id:
                    type: number
                  whitelist:
                    type: array
                    items:
                      oneOf:
                        - type: string
                        - type: object
                          properties:
                            term:
                              type: string
                            info:
                              type: array
                              items:
                                type: string  
        '400':
          description: The organization id was not valid
        '401':
          description: The repo id was not correct
        '409':
          description: Bad key

  /allowlist/add_term/{org_id}/{repo_id}:
    post:
      summary: TODO
      parameters:
        - name: org_id
          in: path
          required: true
          description: The ID of the organization to access
          schema:
            type: integer
        - name: repo_id
          in: path
          required: true
          description: The ID of the repository you are trying to access the whitelist for
          schema:
            type: integer
        - name: term
          in: query
          required: true
          description: the term you are trying to add to the whitelist
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: The organization id was not valid
        '401':
          description: The repo id was not correct
        '402':
          description: The given term was already whitelisted
        '409':
          description: Key error

  /allowlist/add_terms/{org_id}/{repo_id}:
    post:
      summary: TODO
      parameters:
        - name: org_id
          in: path
          required: true
          description: The ID of the organization to access
          schema:
            type: integer
        - name: repo_id
          in: path
          required: true
          description: The ID of the repository you are trying to access the whitelist for
          schema:
            type: integer
        - name: terms
          in: requestBody
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
        '400':
          description: The organization id was not valid
        '401':
          description: The repo id was not correct
        '409':
          description: Bad Key
  
  /allowlist/add_terms_with_info/{org_id}/{repo_id}:
    post:
      summary: TODO
      parameters:
        - name: org_id
          in: path
          required: true
          description: The ID of the organization to access
          schema:
            type: integer
        - name: repo_id
          in: path
          required: true
          description: The ID of the repository you are trying to access the whitelist for
          schema:
            type: integer
        - name: terms
          in: requestBody
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                term:
                  type: string
                info:
                  type: object
                  additionalProperties: true


  /allowlist/remove_term/{org_id}/{repo_id}:
    post:
      summary: TODO
      parameters:
        - name: org_id
          in: path
          required: true
          description: The ID of the organization to access
          schema:
            type: integer
        - name: repo_id
          in: path
          required: true
          description: The ID of the repository you are trying to access the whitelist for
          schema:
            type: integer
        - name: term
          in: query
          required: true
          description: the term you are trying to remove from the whitelist
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: The organization id was not valid
        '401':
          description: The repo id was not correct
        '402':
          description: The given term is not whitelisted
        '409':
          description: Bad Key
