repos:
-   repo: local
    hooks:
    -   id: git-leaks
        name: gitleak_checker
        entry: python3 gitleaks_checker.py
        language: python

# repos:
#     repo: local
#         hooks:
#             -   id: gitleak-checker